### ISSUE TITLE
Basic example error

### ISSUE THREAD

**Issue by PascalLeMerrer** [solher/arangolite#1]
Hi

In the basic example, in the readme, I believe you should switch these 2 lines:

  _, _ := db.Run(&arangolite.CreateCollection{Name: "nodes"})

  db.SwitchDatabase("testDB").SwitchUser("user", "password")

Otherwise you create the collection in the wrong database

**Comment by solher** [comment]
Totally.
Thanks a lot, I'm gonna fix it.

**Comment by PascalLeMerrer** [comment]
BTW, do you have a fully functional example of using arangolite? 
I tried using arangolite and some feature did not work as expected (like collection creation or async queries), but maybe it's my implementation which is wrong. A full project would help me to figure this out.

**Comment by solher** [comment]
I'll try to see if there's something wrong with the basic example.
What kind of problem are you experiencing ?

**Comment by solher** [comment]
(Je ne savais pas qu'Orange s'intéressait à ArangoDB :) )

**Comment by PascalLeMerrer** [comment]
- The node collection is not created.
- the async request returns an empty array

2015-11-30 17:55 GMT+01:00 Fabien Herfray <notifications@github.com>:
