### ISSUE TITLE
Unmarshalling Result Has Duplicate Methods

### ISSUE THREAD

**Issue by ddelger** [solher/arangolite#23]
Response unmarshalling requires wrapping the unmarshalled interface in a result tag.

```
`json"result"`
``` 

I believe this is because both the Unmarshal and UnmarshalResult methods are both operating on the raw response which is enclosed in a result tag. 

```
func (r *response) Unmarshal(v interface{}) error {
	if err := json.Unmarshal(r.raw, v); err != nil {
		return errors.Wrap(err, "response unmarshalling failed")
	}
	return nil
}

func (r *response) UnmarshalResult(v interface{}) error {
	if err := json.Unmarshal(r.raw, v); err != nil {
		return errors.Wrap(err, "response result unmarshalling failed")
	}
	return nil
}
```

I believe UnmarshalResult should be operating on the parsedResponse instead.

**Comment by solher** [comment]
Of course, thanks a lot for reporting it :+1:
