### ISSUE TITLE
database.Run() response result (parsedResponse.Result) always empty

### ISSUE THREAD

**Issue by bendikro** [solher/arangolite#30]
The [`response`](https://github.com/solher/arangolite/blob/v2.0.1/senders.go#L58) object returned by [`database.Send()`](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L163)
is passed to [`database.followCursor()`](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L226)  in the [`database.Run()`](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L168)  function.

When the [`response`](https://github.com/solher/arangolite/blob/v2.0.1/senders.go#L58) object is created in [`senders.Send()`](https://github.com/solher/arangolite/blob/v2.0.1/senders.go#L20), the response's [parsed (parsedResponse)](https://github.com/solher/arangolite/blob/v2.0.1/senders.go#L61) attribute is [`unmarshalled`](https://github.com/solher/arangolite/blob/v2.0.1/senders.go#L40).

It seem the [`parsedResponse.Result`](https://github.com/solher/arangolite/blob/v2.0.1/senders.go#L53) attribute is never populated, and is simply an empty array.

The problem then occurs in [`database.followCursor()`](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L228) where the call to r.RawResult() always returns an empty array, and hence, the result is not unmarshalled into the `v` input argument.

I'm I doing something wrong?

**Comment by solher** [comment]
Just reran some tests and I can't manage to get the same result. Would you have a code sample that reproduces the issue?

**Comment by bendikro** [comment]
Let me try to throw together a test case

**Comment by bendikro** [comment]
@solher 

Check out the tests added in [c2cb80c1](https://github.com/bendikro/arangolite/commit/c2cb80c1384c112160c7f9d4ad8d607888edb628) on this branch: https://github.com/bendikro/arangolite/tree/master-error-tests

The JSON values added to the TestRun() test are the values returned by the database when I test, which are attempted to be unmarshalled at [senders.Send()](https://github.com/solher/arangolite/blob/577fef9aba39b04bc0af2f72e08d7834f1d58512/senders.go#L40)

If you add this code at the beginning of [`followCursor()`](https://github.com/solher/arangolite/blob/577fef9aba39b04bc0af2f72e08d7834f1d58512/database.go#L227)
`fmt.Fprintf(os.Stderr, "Database.followCursor - r.RawResult(): %+v, r.Raw(): %+v\n",
			string(r.RawResult()),
                        string(r.Raw()))`

You will see this output:
`
Database.followCursor - r.RawResult(): , r.Raw(): {"id":"node_port_relations/365","type":"hash","fields":["property"],"selectivityEstimate":0.03125,"unique":false,"sparse":false,"isNewlyCreated":false,"error":false,"code":200}
`
