### ISSUE TITLE
Quote in json value breaks the queries

### ISSUE THREAD

**Issue by PascalLeMerrer** [solher/arangolite#34]
Hi Fabien

When inserting a struct represeting a user, if any field of this user contains a simple quote, the resulting AQL query is invalid:

My code is the following one
```
userJsonBytes, err := json.Marshal(user)
	if err != nil {
		return err
	}
	userJson := string(userJsonBytes)

	query := requests.NewAQL(` UPSERT { "id":"%s" } INSERT %s UPDATE %s IN %s `, user.ID, userJson, userJson, CollectionName)
```
I probably could find a workaround by creating a dedicated json marshaller; but shouldn't the driver prevent this issue?

**Comment by solher** [comment]
Hi Pascal,

The double quotes are definitely already replaced by single quotes. Just added your example as a test and it passes.

May be another bug though. What is the returned error?

**Comment by PascalLeMerrer** [comment]
My example was probably wrong (it was extracted from a larger codebase).

Whatever, it was a non-issue: to solve my problem I just had to use "Bind()"

```
query := requests.NewAQL(` UPSERT { "id":@id } INSERT @userJson UPDATE @userJson IN %s RETURN NEW`, CollectionName)
	query.Bind("id", user.ID)
	query.Bind("userJson", user)
```

and so I don't even have to convert to Json.

**Comment by PascalLeMerrer** [comment]
@solher : You misanderstood the problem.

As written above, the issue occurs when any field of this user contains a **simple** quote

By example if the user name is "O'Hara"
But as I found it, using Bind() solves the issue.
