### ISSUE TITLE
Possibility to get []byte instead of umarshaled struct as result

### ISSUE THREAD

**Issue by sheirys** [solher/arangolite#38]
We are using this lib and extracting large chunks of json. The problem is that these jsons does not have strict structure so they should be unmarshaled only to `map[string]interface{}` for latter use, but in our scenario we do not need to unmarshal json at all and raw `[]byte` of json is ok. It would be nice:

* To have `func (db *Database) GetRaw(ctx context.Context, q Runnable) (json.RawMessage, error)` or equivalent.

Or

* Make `followCursor` as exported so this can be easily achieved with `Send`.

Any opinions?

**Comment by solher** [comment]
If I'm not mistaking, you could simply unmarshal the result into a `json.RawMessage` variable. You would get a `[]byte` without alteration :)

**Comment by sheirys** [comment]
Thanks!
