### ISSUE TITLE
Adding new commands

### ISSUE THREAD

**Issue by PascalLeMerrer** [solher/arangolite#7]
I will extend the driver. I already started with an edge creation feature. But something worries me: in your readme you suggest to add everything in requests.go. So this file could become very long...
I believe the code should be organised by around the business domain, and not the technical notions. By example the create edge request definition should be in edge.go.
Do you agree with this?

**Comment by solher** [comment]
In fact, I just wanted to keep things really clear and separate the driver implementation (models + core querying system) from the implementation of new queries. That's why I wanted to keep those new queries/implementations inside a separate file.
But obviously, I don't have any problem with having it sorted in multiple files like edge_requests.go, database_requests.go, etc.

**Comment by solher** [comment]
And BTW, what kind of edge feature would you like to add ? One can already create edges with AQL so would it be an abstraction ? I don't want to add a lot of ORMish methods and become like AranGO.

**Comment by PascalLeMerrer** [comment]
I'm definitely not wanting to add more features than necessary. 

I wanted to add a create edge feature, but only because I thought it wasn't possible using AQL.
I'm still discovering ArangoDB, so I may be wrong. [This page](https://docs.arangodb.com/Aql/GraphOperations.html) of the documentation lead me to think that only graph reading operations were possible; Am I wrong? If so, how do you create an edge or a graph with AQL?

**Comment by solher** [comment]
To create edges, you can just create an edge collection and insert one inside with a regular
```
INSERT {'_from': 'node/1','_to': 'node/2'} IN edges
```

For graphs, I didn't implemented the HTTP graph API because it is really slow. 
I use the AQL graph functions instead: https://docs.arangodb.com/Aql/GraphFunctions.html

**Comment by PascalLeMerrer** [comment]
Thanks for this information, Fabien.
However, I still think graph creation should be added, as it can't be done through AQL(and I need it in my project. I want the database to be created by the application when it does not exist). Unless you have another wordaround?

**Comment by solher** [comment]
What do you mean when you say it can't be done through AQL ?

The graph API (https://docs.arangodb.com/HttpGharial/index.html) only allows to create graph objects which can be used to simplify AQL queries by using graph operations (https://docs.arangodb.com/Aql/GraphOperations.html) instead of graph functions (https://docs.arangodb.com/Aql/GraphFunctions.html). But in any case, you do it through AQL.

Same question, what do you mean by "I want the database to be created by the application when it does not exist" ? It isn't related to the graph API.

That being said, it would be amazing if you could implement the graph API as it is always good to support more features :)

**Comment by PascalLeMerrer** [comment]
When I say you can't create a graph using AQL, I refer to the graph
management feature <https://docs.arangodb.com/HttpGharial/Management.html>.
Using the HTTP API you may create a graph using a POST request:

```
curl -X POST --data-binary @- --dump - http://localhost:8529/_api/gharial <<EOF
{
  "name" : "myGraph",
  "edgeDefinitions" : [
    {
      "collection" : "edges",
      "from" : [
        "startVertices"
      ],
      "to" : [
        "endVertices"
      ]
    }
  ]
}
```

If my understanding is correct, there is no way to do this using the
current version of arangolite, unless I directly invoke the send
function, isn't it?

When I say "I want the database to be created by the application when it
does not exist", it's a requirement of my application, indeed. I would like
the collections, edge collections and graphs to be created by the app, when
I start it with an empty database. Which implies arangolite should allow me
to send requests to create collections, edge collections and graphs. Hence
my questions. I must admit I forgot the possibility to invoked send(); so
I'll see if I use the low level send method or if extend the driver to add
some graph related features.



2015-12-23 18:26 GMT+01:00 Fabien Herfray <notifications@github.com>:

**Comment by PascalLeMerrer** [comment]
When I say you can't create a graph using AQL, I refer to the [graph
management feature](https://docs.arangodb.com/HttpGharial/Management.html).
Using the HTTP API you may create a graph using a POST request:

```
curl -X POST --data-binary @- --dump - http://localhost:8529/_api/gharial <<EOF
{
  "name" : "myGraph",
  "edgeDefinitions" : [
    {
      "collection" : "edges",
      "from" : [
        "startVertices"
      ],
      "to" : [
        "endVertices"
      ]
    }
  ]
}
```

If my understanding is correct, there is no way to do this using the
current version of arangolite, unless I directly invoke the send
function, isn't it?

When I say "I want the database to be created by the application when it
does not exist", it's a requirement of my application, indeed. I would like
the collections, edge collections and graphs to be created by the app, when
I start it with an empty database. Which implies arangolite should allow me
to send requests to create collections, edge collections and graphs. Hence
my questions. I must admit I forgot the possibility to invoked send(); so
I'll see if I use the low level send method or if extend the driver to add
some graph related features.

**Comment by solher** [comment]
You're totally right.
I'd be glad if you could add it :)

**Comment by solher** [comment]
Merged. Thanks again !
