### ISSUE TITLE
Allow for extension of the library with change to Runnable

### ISSUE THREAD

**Issue by snocorp** [solher/arangolite#9]
I've just started using your library in a project and I really like the API. I can definitely understand wanting to avoid creating an overly complex API as it makes it complicated to maintain and becomes a barrier to adoption.

My use case for Arango is a bit different than the original intent of arangolite in that I need to be able to create documents and perform a few other API calls. Instead of adding bloat to your library, I would like to propose a change to the Runnable interface to allow for extensions to be created instead.

The change would be to export the methods in Runnable as follows:
```go
type Runnable interface {
	Description() string // Description shown in the logger
	Generate() []byte    // The body of the request
	Path() string        // The path where to send the request
	Method() string      // The HTTP method to use
}
```

This would require changing all the existing Runnables in your library but would then allow others to extend the library by simple creating new Runnable implementations and passing them to `DB.Run`.

Let me know if this would be acceptable and I can create a PR to make the changes.

**Comment by solher** [comment]
Done ;)

**Comment by snocorp** [comment]
Awesome, thanks!
